<?php
// Run from CLI: php scripts/seed_demo_data.php [-v]
require __DIR__ . '/../vendor/autoload.php';

use App\Core\Database;
use App\Config\Config;
use App\Models\Role;
use App\Models\Status;
use Mpdf\Mpdf;

if (php_sapi_name() !== 'cli') {
	echo "Please run from CLI: php scripts/seed_demo_data.php\n";
	exit(1);
}

// verbose flag
$verbose = in_array('-v', $argv) || in_array('--verbose', $argv);

// helper password hash
function h(string $p): string
{
	return password_hash($p, PASSWORD_BCRYPT);
}

// Generates a simple PDF (HTML + inline SVG) using mPDF.
// Returns relative public path stored in DB, e.g. "uploads/pdfs/post_123.pdf"
/** @param int $postId
 *  @param string $title
 *  @param string $abstract
 *  @param string $outDir
 *  @return string
 */
function generatePdf(int $postId, string $title, string $abstract, string $outDir): string
{
	if (!class_exists(Mpdf::class)) {
		throw new RuntimeException("mPDF not installed. Run: composer require mpdf/mpdf");
	}

	if (!is_dir($outDir)) {
		mkdir($outDir, 0777, true);
	}

	// pick an SVG illustration (flat or round with a silly caption)
	$svgFlat = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="420" height="180" viewBox="0 0 420 180">
  <rect width="420" height="180" fill="#f5f9ff"/>
  <text x="14" y="28" font-size="18" fill="#222" font-family="Arial">Flat Earth — Definitive Diagram</text>
  <line x1="12" y1="150" x2="408" y2="150" stroke="#0b66a0" stroke-width="4" />
  <circle cx="60" cy="120" r="14" fill="#ffc107" />
  <text x="82" y="128" font-size="12" fill="#333">Sun (moves above the plate)</text>
  <text x="14" y="160" font-size="10" fill="#555">Figure: The horizon = edge of plate. No curvature visible.</text>
</svg>
SVG;

	$svgRound = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="420" height="180" viewBox="0 0 420 180">
  <rect width="420" height="180" fill="#fff7f0"/>
  <text x="14" y="28" font-size="18" fill="#222" font-family="Arial">Round Earth — Optical Illusion</text>
  <circle cx="210" cy="95" r="48" stroke="#c62828" stroke-width="3" fill="none" />
  <text x="14" y="160" font-size="10" fill="#555">Figure: They draw a circle and call it evidence. We disagree.</text>
</svg>
SVG;

	$svg = (rand(0, 1) === 1) ? $svgFlat : $svgRound;

	// Build HTML content - keep it simple and printable
	$html = '<html><head><meta charset="utf-8"><style>
        body{font-family: DejaVu Sans, Arial, sans-serif; font-size:12pt; color:#222}
        h1{font-size:20pt; margin-bottom:6px}
        p.abstract{font-size:11pt; line-height:1.35; margin-top:0}
        .meta{font-size:10pt; color:#666; margin-bottom:12px}
        .svg-wrap{margin:12px 0}
        .foot{font-size:9pt; color:#666; margin-top:18px}
        </style></head><body>';
	$html .= '<h1>' . htmlspecialchars($title) . '</h1>';
	$html .= '<div class="meta">Flat Earth Society Conference — auto-generated demo PDF for presentation #' . $postId . '</div>';
	$html .= '<p class="abstract">' . nl2br(htmlspecialchars($abstract)) . '</p>';
	$html .= '<div class="svg-wrap">' . $svg . '</div>';
	$html .= '<div class="foot">This PDF was generated by the seeder for demo purposes.</div>';
	$html .= '</body></html>';

	$filename = 'post_' . $postId . '.pdf';
	$fullPath = rtrim($outDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $filename;

	$mpdf = new Mpdf(['mode' => 'utf-8']);
	$mpdf->WriteHTML($html);
	$mpdf->Output($fullPath, \Mpdf\Output\Destination::FILE);

	// return path relative to webroot/public
	return 'uploads/pdfs/' . $filename;
}

try {
	$db = new Database();

	// make sure output dir exists and is writable
	$pdfDirFull = __DIR__ . '/../public/uploads/pdfs';
	if (!is_dir($pdfDirFull)) {
		mkdir($pdfDirFull, 0777, true);
	}

	// -------------------------------------------------------------------------
	// Data sets
	// -------------------------------------------------------------------------
	$first = ['Flat', 'Round', 'Spinning', 'Wobbly', 'Gravityless', 'Moonbeam', 'Compass', 'Pole', 'Skewed', 'Tilted', 'Sky', 'Horizon', 'Tinfoil', 'Feather', 'Quirky', 'Crispy', 'Bouncy'];
	$last  = ['Jones', 'McGee', "O'Flat", 'Vanishing', 'Sprocket', 'Turner', 'Fitz', 'McHollow', 'Droplet', 'Featherstone', 'Noodle', 'Wren', 'Pancake', 'Whimsy', 'Loop'];
	$adjectives = ['Professor', 'Dr', 'Sir', 'Madam', 'Captain', 'Agent', 'Mister', 'Ms'];
	$funPasswords = ['flatIsFun', 'noGravity!', 'pancake42', 'tilt&spin', 'gravity?no', 'round?nah', 'horiz0n', 'tinfoilHat', 'beacon123', 'coriolis'];

	$ROLE_AUTHOR = Role::Author->value;
	$ROLE_REVIEWER = Role::Reviewer->value;
	$ROLE_ADMIN = Role::Admin->value;
	$ROLE_SUPER = Role::Superadmin->value;

	// -------------------------------------------------------------------------
	// Ensure superadmin
	// -------------------------------------------------------------------------
	echo "== Seeding users ==\n";
	$db->query("INSERT IGNORE INTO users (username, passwordHash, name, role) VALUES (:u,:p,:n,:r)")
		->bind(':u', 'supremus')
		->bind(':p', h('superfun'))
		->bind(':n', 'Supreme Admin')
		->bind(':r', $ROLE_SUPER)
		->execute();

	// helper inserter
	$insertUsers = function (int $count, int $role, string $prefix) use ($db, $first, $last, $adjectives, $funPasswords, $verbose) {
		$created = 0;
		$tries = 0;
		while ($created < $count && $tries < $count * 6) {
			$tries++;
			$fn = $first[array_rand($first)];
			$ln = $last[array_rand($last)];
			$adj = $adjectives[array_rand($adjectives)];
			// username cleaned: letters + digits only
			$username = strtolower($prefix . '_' . preg_replace('/[^a-z0-9]/', '', $fn . substr($ln, 0, 3)));
			$name = "$adj $fn $ln";
			$pwd = $funPasswords[array_rand($funPasswords)] . rand(1, 99);

			try {
				$db->query("INSERT INTO users (username, passwordHash, name, role) VALUES (:username,:ph,:name,:role)")
					->bind(':username', $username)
					->bind(':ph', h($pwd))
					->bind(':name', $name)
					->bind(':role', $role)
					->execute();
				$created++;
				if ($verbose) echo " - created user $username (role=$role)\n";
			} catch (\Throwable $e) {
				// duplicate or other issue - skip and continue
				continue;
			}
		}
		return $created;
	};

	$adminsCreated = $insertUsers(8, $ROLE_ADMIN, 'admin');
	$authorsCreated = $insertUsers(15, $ROLE_AUTHOR, 'author');
	$reviewersCreated = $insertUsers(15, $ROLE_REVIEWER, 'rev');

	if (!$verbose) {
		echo "Users: admins=$adminsCreated authors=$authorsCreated reviewers=$reviewersCreated\n\n";
	}

	// fetch ids by role
	$rolesToIds = function (int $role) use ($db) {
		$rows = $db->query("SELECT id FROM users WHERE role = :r")
			->bind(':r', $role)
			->fetchAll();
		return array_map(fn($r) => (int)$r['id'], $rows);
	};

	$authorIds = $rolesToIds($ROLE_AUTHOR);
	$reviewerIds = $rolesToIds($ROLE_REVIEWER);

	if (count($authorIds) < 3) {
		throw new RuntimeException("Not enough authors seeded (need >=3).");
	}
	if (count($reviewerIds) < 5) {
		throw new RuntimeException("Not enough reviewers seeded (need >=5).");
	}

	// -------------------------------------------------------------------------
	// Create posts (20 per Status case)
	// -------------------------------------------------------------------------
	echo "== Creating posts and PDFs ==\n";

	$lorem = [
		"Exploring why the horizon never curves in airplane windows.",
		"A hilarious deep dive into the mystery of disappearing satellites.",
		"Experimental tests with laser pointers and pancake plates.",
		"Flat-earth mapping: how to measure the world without curvature.",
		"Evidence that gravity is just a conspiracy by round-earthers.",
		"Using moonbeams to prove the Earth is perfectly level.",
		"The secret physics of wobbling compasses and skewed shadows.",
		"Practical guide to presenting flat-earth arguments at parties.",
		"Social psychology of flat-earth believers and skeptics alike.",
		"Demonstrating a round-earth illusion with everyday kitchen tools."
	];

	$postIdsByStatus = [];

	foreach (Status::cases() as $status) {
		$postIdsByStatus[$status->value] = [];
		for ($i = 0; $i < 20; $i++) {
			// title should be clean (no weird numbers/symbols)
			$title = ucfirst($lorem[array_rand($lorem)]);
			// move identifying random bits into abstract (so title remains clean)
			$abstract = $lorem[array_rand($lorem)]
				. "\n\nSeed details: " . substr(md5(rand()), 0, 10) . " — this is a humorous abstract generated for the Flat Earth Society Conference. "
				. "It contains long descriptions, playful claims, and absurd methods for measuring horizon flatness.";
			$authorId = $authorIds[array_rand($authorIds)];

			$db->query("INSERT INTO posts (userId, title, abstract, pathPDF, status) VALUES (:uid,:title,:abstract,'',:status)")
				->bind(':uid', $authorId)
				->bind(':title', $title)
				->bind(':abstract', $abstract)
				->bind(':status', $status->value)
				->execute();

			// get inserted post id
			$row = $db->query("SELECT id FROM posts WHERE title = :title ORDER BY id DESC LIMIT 1")
				->bind(':title', $title)
				->fetchFirst();
			$postId = (int)$row['id'];
			$postIdsByStatus[$status->value][] = $postId;

			// generate PDF and update DB
			try {
				$pdfRel = generatePdf($postId, $title, $abstract, $pdfDirFull);
				$db->query("UPDATE posts SET pathPDF = :pdf WHERE id = :id")
					->bind(':pdf', $pdfRel)
					->bind(':id', $postId)
					->execute();
				if ($verbose) echo " - created post #$postId (status={$status->label()}) with PDF $pdfRel\n";
			} catch (\Throwable $e) {
				// If PDF generation fails, continue but warn
				echo " ! PDF generation failed for post $postId: " . $e->getMessage() . "\n";
			}
		}
	}

	// summary if not verbose
	if (!$verbose) {
		foreach ($postIdsByStatus as $st => $ids) {
			echo count($ids) . " posts with status " . Status::from($st)->label() . "\n";
		}
	}

	// -------------------------------------------------------------------------
	// Assign reviewers & create reviews
	// - Ensure accepted/rejected posts have at least 3 reviewers and 3 reviews
	// -------------------------------------------------------------------------
	echo "== Assigning reviewers and creating reviews ==\n";

	$notes = [
		"Thoroughly convincing — would attend the talk.",
		"Interesting ideas but needs more solid evidence.",
		"Good methodology, some gaps in measurement.",
		"Entertaining and creative, presentation recommended.",
		"Findings are questionable — suggest revisions.",
		"Solid demonstration, minor corrections suggested."
	];

	$totalReviews = 0;
	$assignedPairs = 0;

	foreach ($postIdsByStatus as $statusValue => $posts) {
		foreach ($posts as $postId) {
			// min 3 assigned if published/rejected
			$minAssign = in_array($statusValue, [Status::Accepted->value, Status::Rejected->value]) ? 3 : 1;
			$assignCount = rand($minAssign, 5);
			$shuffled = $reviewerIds;
			shuffle($shuffled);
			$assign = array_slice($shuffled, 0, $assignCount);

			foreach ($assign as $rid) {
				$db->query("INSERT IGNORE INTO post_reviewer (postId, userId) VALUES (:pid,:uid)")
					->bind(':pid', $postId)
					->bind(':uid', $rid)
					->execute();
				$assignedPairs++;
				if ($verbose) echo " -- post $postId assigned reviewer $rid\n";
			}

			// create reviews: ensure at least minAssign reviews for accepted/rejected posts
			$reviewsToCreate = max($minAssign, rand(1, min(5, count($assign))));
			$selected = array_slice($assign, 0, $reviewsToCreate);

			foreach ($selected as $revId) {
				$db->query("
                    INSERT IGNORE INTO reviews (postId, userId, ratingInteresting, ratingImportant, ratingInovative, ratingNote)
                    VALUES (:pid,:uid,:ri,:rj,:rk,:note)
                ")
					->bind(':pid', $postId)
					->bind(':uid', $revId)
					->bind(':ri', rand(1, 5))
					->bind(':rj', rand(1, 5))
					->bind(':rk', rand(1, 5))
					->bind(':note', $notes[array_rand($notes)])
					->execute();
				$totalReviews++;
				if ($verbose) echo " --- review added by $revId for post $postId\n";
			}
		}
	}

	// final summary
	echo "\nSeeding complete.\n";
	// counts summary (compact)
	$countsUsers = $db->query("SELECT role, COUNT(*) AS cnt FROM users GROUP BY role")->fetchAll();
	$roleNames = [];
	foreach ($countsUsers as $r) {
		try {
			$roleNames[$r['role']] = \App\Models\Role::from((int)$r['role'])->name;
		} catch (\Throwable $e) {
			$roleNames[$r['role']] = 'role_' . $r['role'];
		}
	}
	echo "Users by role:\n";
	foreach ($countsUsers as $r) {
		$label = $roleNames[$r['role']] ?? $r['role'];
		echo " - {$label}: {$r['cnt']}\n";
	}

	$postCounts = $db->query("SELECT status, COUNT(*) AS cnt FROM posts GROUP BY status")->fetchAll();
	echo "Posts by status:\n";
	foreach ($postCounts as $p) {
		$label = Status::from((int)$p['status'])->label();
		echo " - {$label}: {$p['cnt']}\n";
	}

	$totalAssigned = $db->query("SELECT COUNT(*) AS c FROM post_reviewer")->fetchFirst()['c'] ?? 0;
	$totalReviewsDb = $db->query("SELECT COUNT(*) AS c FROM reviews")->fetchFirst()['c'] ?? 0;

	echo "Total assigned reviewer pairs: $totalAssigned\n";
	echo "Total reviews: $totalReviewsDb\n";

	if ($verbose) {
		// detailed listing
		echo "\nDetailed lists (users, posts, reviews):\n";
		// users
		$users = $db->query("SELECT id, username, name, role FROM users ORDER BY role, username")->fetchAll();
		echo "\nUsers:\n";
		foreach ($users as $u) {
			$rname = Status::tryFrom((int)$u['role']) ? Status::from((int)$u['role'])->label() : ($roleNames[$u['role']] ?? $u['role']);
			echo " - {$u['id']} {$u['username']} ({$u['name']}) role={$u['role']}\n";
		}
		// posts sample
		$posts = $db->query("SELECT id, title, status, pathPDF FROM posts ORDER BY id")->fetchAll();
		echo "\nPosts:\n";
		foreach ($posts as $p) {
			$st = Status::from((int)$p['status'])->label();
			echo " - {$p['id']} [{$st}] {$p['title']} pdf={$p['pathPDF']}\n";
		}
		// reviews sample
		$revs = $db->query("SELECT id, postId, userId, ratingInteresting, ratingImportant, ratingInovative FROM reviews ORDER BY id")->fetchAll();
		echo "\nReviews (count=" . count($revs) . "):\n";
		foreach ($revs as $r) {
			echo " - {$r['id']} post={$r['postId']} user={$r['userId']} ({$r['ratingInteresting']},{$r['ratingImportant']},{$r['ratingInovative']})\n";
		}
	}

	echo "\nDone.\n";
	exit(0);
} catch (\Throwable $e) {
	echo "Error while seeding: " . $e->getMessage() . "\n";
	exit(1);
}
