<?php
// scripts/seed_posts_by_authors.php
// Usage:
//   php scripts/seed_posts_by_authors.php        # create posts (1..5) per author
//   php scripts/seed_posts_by_authors.php -v     # verbose
//   php scripts/seed_posts_by_authors.php --pdf  # also attempt to create PDFs (requires mpdf/mpdf)
//   php scripts/seed_posts_by_authors.php --pdf -v
require __DIR__ . '/../vendor/autoload.php';

use App\Core\Database;
use App\Models\Role;
use App\Models\Status;
use Mpdf\Mpdf;

if (php_sapi_name() !== 'cli') {
	echo "Run from CLI: php scripts/seed_posts_by_authors.php\n";
	exit(1);
}

$argv_flags = $argv;
array_shift($argv_flags); // remove script name

$verbose = in_array('-v', $argv_flags, true) || in_array('--verbose', $argv_flags, true);
$doPdf = in_array('--pdf', $argv_flags, true);

function logv(string $s)
{
	global $verbose;
	if ($verbose) {
		echo $s . PHP_EOL;
	}
}

// helper random text (funny / flat-earth themed)
$lorem = [
	"Exploring why the horizon never curves in airplane windows.",
	"A hilarious deep dive into the mystery of disappearing satellites.",
	"Experimental tests with laser pointers and pancake plates.",
	"Flat-earth mapping: how to measure the world without curvature.",
	"Evidence that gravity is just a conspiracy by round-earthers.",
	"Using moonbeams to prove the Earth is perfectly level.",
	"The secret physics of wobbling compasses and skewed shadows.",
	"Practical guide to presenting flat-earth arguments at parties.",
	"Social psychology of flat-earth believers and skeptics alike.",
	"Demonstrating a round-earth illusion with everyday kitchen tools.",
	"Crowdsourced horizon measurements and the art of selective data.",
	"How to fold a map when the world is a plate, not a globe."
];

function rand_abstract(array $lorem): string
{
	$parts = [];
	$sentences = rand(3, 6);
	for ($i = 0; $i < $sentences; $i++) {
		$parts[] = $lorem[array_rand($lorem)];
	}
	// put identification/random bits into abstract
	$parts[] = "Seed details: " . substr(md5((string)rand()), 0, 10) . " — humorous auto-generated abstract for demo.";
	return implode("\n\n", $parts);
}

function make_clean_title(array $lorem): string
{
	// pick a line and strip punctuation/digits — keep it short and clean
	$t = $lorem[array_rand($lorem)];
	// remove characters that are not letters, space or basic punctuation we allow (keep commas/colon)
	$t = preg_replace('/[^\p{L}\p{N}\s\-,:]/u', '', $t);
	// remove numbers
	$t = preg_replace('/\d+/', '', $t);
	// limit to ~80 chars
	$t = trim(mb_substr($t, 0, 80));
	return rtrim($t, ",-:");
}

// optional PDF generator using mPDF (returns filename or empty on failure)
function generatePdfForPost(int $postId, string $title, string $abstract, string $outDir): string
{
	if (!class_exists(\Mpdf\Mpdf::class)) {
		throw new RuntimeException("mPDF not installed. Install with: composer require mpdf/mpdf");
	}

	if (!is_dir($outDir) && !mkdir($outDir, 0777, true) && !is_dir($outDir)) {
		throw new RuntimeException("Failed to create PDF output directory: $outDir");
	}

	// simple SVG illustration (random)
	$svgFlat = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="420" height="160" viewBox="0 0 420 160">
  <rect width="420" height="160" fill="#f6fbff"/>
  <text x="14" y="24" font-size="16" fill="#222" font-family="DejaVu Sans">Flat Earth — Demonstration Diagram</text>
  <line x1="12" y1="130" x2="408" y2="130" stroke="#0b66a0" stroke-width="3" />
  <circle cx="60" cy="100" r="10" fill="#ffc107" />
  <text x="82" y="108" font-size="10" fill="#333">Sun (moves above the plate)</text>
</svg>
SVG;

	$svgRound = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="420" height="160" viewBox="0 0 420 160">
  <rect width="420" height="160" fill="#fff7f7"/>
  <text x="14" y="24" font-size="16" fill="#222" font-family="DejaVu Sans">Round Earth — Cartoon</text>
  <circle cx="210" cy="80" r="36" stroke="#c62828" stroke-width="3" fill="none" />
  <text x="14" y="144" font-size="10" fill="#555">Figure: round-earth drawing (we disagree).</text>
</svg>
SVG;

	$svg = rand(0, 1) ? $svgFlat : $svgRound;

	$html = '<html><head><meta charset="utf-8"><style>
        body{font-family: DejaVu Sans, Arial, sans-serif; font-size:12pt; color:#222}
        h1{font-size:18pt; margin-bottom:6px}
        p{font-size:11pt; line-height:1.35}
        .meta{font-size:9pt; color:#666}
        .svg{margin-top:10px}
        </style></head><body>';
	$html .= '<h1>' . htmlspecialchars($title) . '</h1>';
	$html .= '<div class="meta">Auto-generated demo PDF for presentation #' . $postId . '</div>';
	$html .= '<p>' . nl2br(htmlspecialchars($abstract)) . '</p>';
	$html .= '<div class="svg">' . $svg . '</div>';
	$html .= '<div class="meta" style="margin-top:10px;">Generated by seeder</div>';
	$html .= '</body></html>';

	$filename = 'post_' . $postId . '.pdf';
	$fullPath = rtrim($outDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $filename;

	$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8']);
	$mpdf->WriteHTML($html);
	$mpdf->Output($fullPath, \Mpdf\Output\Destination::FILE);

	return $filename;
}

try {
	$db = new Database();

	// find authors
	$authors = $db->query("SELECT id, username, name FROM users WHERE role = :role ORDER BY id")
		->bind(':role', Role::Author->value)
		->fetchAll();

	if (!$authors) {
		echo "No authors found in users table (role=Author). Nothing to do.\n";
		exit(0);
	}

	$outPdfDir = __DIR__ . '/../public/uploads';
	if ($doPdf && !is_dir($outPdfDir) && !mkdir($outPdfDir, 0777, true) && !is_dir($outPdfDir)) {
		throw new RuntimeException("Failed to create upload directory: $outPdfDir");
	}

	$createdTotal = 0;
	$perAuthor = [];

	foreach ($authors as $a) {
		$authorId = (int)$a['id'];
		$authorName = $a['name'] ?? $a['username'];
		$num = rand(1, 5);
		$perAuthor[$authorId] = $num;
		logv("Author #$authorId ({$authorName}) -> creating $num post(s)");

		for ($i = 0; $i < $num; $i++) {
			$title = make_clean_title($lorem);
			$abstract = rand_abstract($lorem);

			// default status: PendingReview
			$status = Status::PendingReview->value;

			$db->query("INSERT INTO posts (userId, title, abstract, pathPDF, status) VALUES (:uid,:title,:abstract,'',:status)")
				->bind(':uid', $authorId)
				->bind(':title', $title)
				->bind(':abstract', $abstract)
				->bind(':status', $status)
				->execute();

			// get inserted id
			$row = $db->query("SELECT id FROM posts WHERE title = :title AND userId = :uid ORDER BY id DESC LIMIT 1")
				->bind(':title', $title)
				->bind(':uid', $authorId)
				->fetchFirst();
			$postId = (int)$row['id'];

			// optionally create pdf
			if ($doPdf) {
				try {
					if (!class_exists(\Mpdf\Mpdf::class)) {
						// if mpdf unavailable, warn once and skip remaining pdfs
						echo "Warning: mPDF not installed; skipping PDF generation. Install with: composer require mpdf/mpdf\n";
						$doPdf = false;
					} else {
						$pdfRel = generatePdfForPost($postId, $title, $abstract, $outPdfDir);
						// update post record
						$db->query("UPDATE posts SET pathPDF = :pdf WHERE id = :id")
							->bind(':pdf', $pdfRel)
							->bind(':id', $postId)
							->execute();
						logv(" - created PDF for post $postId: $pdfRel");
					}
				} catch (\Throwable $e) {
					echo " ! PDF generation failed for post {$postId}: " . $e->getMessage() . PHP_EOL;
				}
			}

			$createdTotal++;
			logv(" -> created post #$postId for author #$authorId");
		}
	}

	// summary
	echo "Done: created {$createdTotal} posts for " . count($authors) . " author(s)." . PHP_EOL;
	echo "Details per author (authorId => created):" . PHP_EOL;
	foreach ($perAuthor as $aid => $count) {
		echo " - {$aid}: {$count}\n";
	}

	// print DB totals for posts
	$tot = $db->query("SELECT status, COUNT(*) AS c FROM posts GROUP BY status")->fetchAll();
	echo "Posts by status:\n";
	foreach ($tot as $t) {
		try {
			$label = Status::from((int)$t['status'])->label();
		} catch (\Throwable $e) {
			$label = (string)$t['status'];
		}
		echo " - {$label}: {$t['c']}\n";
	}

	exit(0);
} catch (\Throwable $e) {
	fwrite(STDERR, "Error: " . $e->getMessage() . PHP_EOL);
	exit(1);
}
